hsp = 0
vsp = 0
movespeed = 3
grv = 0.1
dir = 1
move = 0
flightspeed = 5
ground = 1
state = "normal"
spining = 0
warpin = 0
hallway		= false;			// Hallway
hallwaydir	= 1;				// Hallway Direction
targetDoor	= "A";				// Target Door
vhallway	= false;			// Vertical Hallway
vhallwaydir = 1;				// Vertical Hallway Direction
timer = 0
start_timer = true